name: wallpaper
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  animated_flip_counter: ^0.3.4
  lottie: ^3.2.0
  flutter_svg: ^2.0.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.1
  pull_down_button: ^0.10.2
  pinch_zoom: ^2.0.1
  pinput: ^5.0.1

  # Styling
  google_fonts: ^6.2.1

  # Navigation
  go_router: ^15.0.0

  # Storage & State
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  # Media & Files
  image_picker: ^1.1.2

  # Network & Utilities
  http: ^1.3.0
  url_launcher: ^6.3.1
  ntp: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    #  - assets/png/
    - assets/svg/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SFPro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFPro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFPro/SF-Pro-Display-Semibold.otf
          weight: 600
