name: wallpaper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.0.0
  iconly: ^1.0.1
  animated_flip_counter: ^0.3.4
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  pull_down_button: ^0.10.2
  pinch_zoom: ^2.0.1
  image_picker: ^1.1.2
  ntp: ^2.0.0
  pinput: ^5.0.1
  http: ^1.3.0
  url_launcher: ^6.3.1
  skeletonizer: ^1.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
